### ISSUE TITLE
JSONDecodeError: <Response [404]>

### ISSUE THREAD

**Issue by PeanutAria** [Spicadox/auto-twitter-space#9]
```
2023-07-01 05:48:03 [index.py:490] INFO     Starting program
2023-07-01 05:48:04 [index.py:97] DEBUG    Renewed Guest Token: 1674897688343752704
2023-07-01 05:48:04 [index.py:183] DEBUG    [▪️▪️▪️] JSONDecodeError: <Response [404]>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\!monitoring tools\auto-twitter-space\index.py", line 181, in get_space_tweet_id
    rest_id_json = rest_id_response.json()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Just found out that we can no longer browse Twitter without an account, does this error has something to do with it? Is there anyway to make this script works again?

UPDATE:
Found this tweet from a Twitter staff, don't know whether to share it here or not but just in case
![2023-07-01 06_09_09-Aqueel_on_Twitter_@t3dotgg_this_is_a_temporary_res](https://github.com/Spicadox/auto-twitter-space/assets/121492287/587e2540-b429-4623-a2b0-06d570803d43)
😕

**Comment by Spicadox** [comment]
Yep...thanks twitter...

As you've suspected, the issue is indeed with guest access being blocked and as such, the api endpoints aren't working. 

Though, playing around with it earlier, I've gotten the new api endpoints to work, but now, it's a matter of actually coding it with new means of authenticating the requests. Due to needing authentication now, I'm just a little weary on possibly getting rate-limited while being authenticated, but that's a different issue.

**Comment by Spicadox** [comment]
Latest code has been pushed and should be working now. Had to update to new api endpoints that require new methods of authentication. New changes require manually getting `auth_token` and `ct0` value from the browser and putting it in `const.py`. Not sure as of now the expiry time of the token and `SLEEP_TIME` will have to be adjusted to avoid getting rate-limited. Default is 2 seconds but as of now 1.5 seconds seems to be fine to avoid the requests from getting rate-limited.

**Comment by PeanutAria** [comment]
Can confirmed it works. I'll open a new ticket if there's another problem but so far, it's working fine. Thank you so much 😊
